import { Inter } from "next/font/google";
import { Hachi_Maru_Pop } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });
const HachiMaruPopFont = Hachi_Maru_Pop({ weight: "400", subsets: ["latin"] });

export const metadata = {
  title: "じ-ないん",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={HachiMaruPopFont.className}>{children}</body>
    </html>
  );
}
